### ISSUE TITLE
请教训练数据集问题

### ISSUE THREAD

**Issue by yang-chenyu104** [ZYM-PKU/UDiffText#3]
可以训练中文数据集吗

**Comment by ZYM-PKU** [comment]
理论上是可行的，但是需要具有单字级别标注的高质量数据集

**Comment by yang-chenyu104** [comment]
那可以训练一个中文编码器，用文本检测器将文本区域检测，然后做一个中文文本编辑模型



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZYM-PKU/UDiffText] 请教训练数据集问题 (Issue #3)




 
理论上是可行的，但是需要具有单字级别标注的高质量数据集

**Comment by yang-chenyu104** [comment]
谢谢大佬分享工作，启发很多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZYM-PKU/UDiffText] 请教训练数据集问题 (Issue #3)




 
理论上是可行的，但是需要具有单字级别标注的高质量数据集

**Comment by ZYM-PKU** [comment]
这个想法很棒，我也会在接下来的工作中考虑类似的方法，感谢。

**Comment by yang-chenyu104** [comment]
可以多多交流！！！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 晚上9:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZYM-PKU/UDiffText] 请教训练数据集问题 (Issue #3)




 
这个想法很棒，我也会在接下来的工作中考虑类似的方法，感谢。

**Comment by fh1999** [comment]
Hi~ 我发现ViTSTR不支持中文，微调时clip_loss难以收敛,是否有替代的模型～
